import { Task } from '@/src/types';
import { format, addDays } from 'date-fns';

const iso = (offset: number) => format(addDays(new Date(), offset), 'yyyy-MM-dd');

export const seedTasks: Task[] = [
  {
    id: 'seed-1',
    title: 'Quarterly Resource Audit',
    description: 'Finance & Strategy Department review of Q3 spend against the studio budget.',
    priority: 'High',
    status: 'Pending',
    dueDate: iso(0),
    time: '10:00 AM',
    tags: ['Finance', 'Strategy'],
    category: 'Work',
  },
  {
    id: 'seed-2',
    title: 'System Architecture Review',
    description: 'Infrastructure team sync to validate the new service boundaries before rollout.',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: iso(0),
    time: '02:30 PM',
    tags: ['Engineering', 'Infrastructure'],
    category: 'Work',
  },
  {
    id: 'seed-3',
    title: 'Personal Wellness Check-in',
    description: 'Routine maintenance — stretch, hydrate, breathe.',
    priority: 'Low',
    status: 'Pending',
    dueDate: iso(0),
    time: '05:00 PM',
    tags: ['Routine'],
    category: 'Health',
  },
  {
    id: 'seed-4',
    title: 'Refactor the Design System Documentation',
    description: 'Ensure all tokens map correctly to the new Tailwind configuration and update the accessibility guidelines for ghost borders.',
    priority: 'High',
    status: 'Pending',
    dueDate: iso(1),
    tags: ['Engineering', 'Design'],
    category: 'Work',
  },
  {
    id: 'seed-5',
    title: 'Weekly Synchronized Review',
    description: 'Gather metrics from the last sprint and prepare the deck for the Friday stakeholder presentation.',
    priority: 'Medium',
    status: 'Pending',
    dueDate: iso(2),
    tags: ['Management'],
    category: 'Work',
  },
  {
    id: 'seed-6',
    title: 'Audit Color Contrast',
    description: 'Run WCAG 2.1 compliance check on the new Indigo palette variants.',
    priority: 'Medium',
    status: 'Completed',
    dueDate: iso(-1),
    tags: ['Design'],
    category: 'Work',
  },
  {
    id: 'seed-7',
    title: 'Update Asset Library',
    description: 'Prune unused icons and export latest SVG set for the development team.',
    priority: 'Low',
    status: 'Pending',
    dueDate: iso(6),
    tags: ['Assets'],
    category: 'Personal',
  },
  {
    id: 'seed-8',
    title: 'Inbox Zero Session',
    description: 'Clear the backlog before the week resets.',
    priority: 'Low',
    status: 'Completed',
    dueDate: iso(-2),
    time: '08:00 AM',
    tags: ['Admin'],
    category: 'Personal',
  },
];
