import { Task } from '@/src/types';
import { format, addDays } from 'date-fns';

const iso = (offset: number) => format(addDays(new Date(), offset), 'yyyy-MM-dd');

export const seedTasks: Task[] = [
  {
    id: 'seed-1',
    title: 'Квартальный аудит ресурсов',
    description: 'Проверка отделом финансов и стратегии расходов за Q3 в рамках бюджета студии.',
    priority: 'High',
    status: 'Pending',
    dueDate: iso(0),
    time: '10:00',
    tags: ['Финансы', 'Стратегия'],
    category: 'Work',
  },
  {
    id: 'seed-2',
    title: 'Обзор архитектуры системы',
    description: 'Синхронизация с инфраструктурной командой для проверки новых границ сервисов перед релизом.',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: iso(0),
    time: '14:30',
    tags: ['Разработка', 'Инфраструктура'],
    category: 'Work',
  },
  {
    id: 'seed-3',
    title: 'Забота о самочувствии',
    description: 'Плановая пауза — растяжка, вода, дыхание.',
    priority: 'Low',
    status: 'Pending',
    dueDate: iso(0),
    time: '17:00',
    tags: ['Рутина'],
    category: 'Health',
  },
  {
    id: 'seed-4',
    title: 'Рефакторинг документации дизайн-системы',
    description: 'Убедиться, что все токены корректно отображены в новой конфигурации Tailwind, и обновить рекомендации по доступности для призрачных рамок.',
    priority: 'High',
    status: 'Pending',
    dueDate: iso(1),
    tags: ['Разработка', 'Дизайн'],
    category: 'Work',
  },
  {
    id: 'seed-5',
    title: 'Еженедельный синхронный обзор',
    description: 'Собрать метрики за последний спринт и подготовить презентацию для пятничной встречи с заинтересованными лицами.',
    priority: 'Medium',
    status: 'Pending',
    dueDate: iso(2),
    tags: ['Менеджмент'],
    category: 'Work',
  },
  {
    id: 'seed-6',
    title: 'Аудит цветового контраста',
    description: 'Проверка соответствия WCAG 2.1 для новых тональных вариантов индиго-палитры.',
    priority: 'Medium',
    status: 'Completed',
    dueDate: iso(-1),
    tags: ['Дизайн'],
    category: 'Work',
  },
  {
    id: 'seed-7',
    title: 'Обновление библиотеки ассетов',
    description: 'Убрать неиспользуемые иконки и экспортировать актуальный набор SVG для команды разработки.',
    priority: 'Low',
    status: 'Pending',
    dueDate: iso(6),
    tags: ['Ассеты'],
    category: 'Personal',
  },
  {
    id: 'seed-8',
    title: 'Разбор входящих до нуля',
    description: 'Очистить накопившиеся письма перед началом новой недели.',
    priority: 'Low',
    status: 'Completed',
    dueDate: iso(-2),
    time: '08:00',
    tags: ['Админ'],
    category: 'Personal',
  },
];
